### ISSUE TITLE
Not able to execute the command : npm install seneca —save

### ISSUE THREAD

**Issue by satyamsah** [airavata-courses/madrinathapa#1]
npm install seneca —save

npm ERR! addLocal Could not install /home/ubuntuaws/myvirtualenv/madrinathapa/—save
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "seneca" "—save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /home/ubuntuaws/myvirtualenv/madrinathapa/—save
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntuaws/myvirtualenv/madrinathapa/—save'
npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntuaws/myvirtualenv/madrinathapa/—save'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntuaws/myvirtualenv/madrinathapa/npm-debug.log

Could you please check for proper dependency

**Comment by madrinathapa** [comment]
Hi Satyam,

I think there is a typo. Can you please try to execute (npm install seneca --save) ?
p.s It is a usual npm install command with a save option. 

Thank you,
Madrina Thapa

**Comment by satyamsah** [comment]
Could you please check if there is no typo in the other commands and let me know if whenever you have updated the repository.

**Comment by satyamsah** [comment]
Could you please check if there is no typo in the other commands and let me know whenever you have updated the repository. So that I need not to re-open the issue.

I hope I am not bugging you :)

**Comment by marpierc** [comment]
Note you can associate commits with issues in GitHub.
