### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/madrinathapa#10]
The 3 microservices are working fine and are exposed through an API server to the UI. 

Things to be noted -
There is no architecture diagram explaining how the services are called. 
The README.md has not been moved to the Wiki.

**Comment by madrinathapa** [comment]
Hi Sneha,

I have added a diagram and have also updated the wiki.

Thank you,
Madrina Thapa

**Comment by tilaks26** [comment]
Thanks, Madrina.

**Comment by tilaks26** [comment]
Can you also correct your steps? The installation steps, I mean. Like the one where you are running the java sprint boot file as well as the JAR.
Also, use the Wiki for all information regarding the assignment. I would suggest you to maintain a page for each assignment and include all prerequisites, dependencies and installation steps under the respective assignment pages.
