### ISSUE TITLE
Assignment 2: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/madrinathapa#14]
Hi Madrina,

I verified the Docker and the RMQ setup, and looks good to me. Could email me the jenkins credentials so that I can review that as well? Also can you mention whether the Jenkins is set to push / pull or is it manually setup right now.

**Comment by madrinathapa** [comment]
Hello Ameya,

I have shared my credentials with you. Please let me know if there is something else you need. 

Thank you,
Madrina Thapa

**Comment by Ameya05** [comment]
Verified the Jenkins setup, it is setup properly. 
Entire System is working as expected.
