### ISSUE TITLE
Cannot find module 'seneca-web' and 'seneca' in "hello-world" service 

### ISSUE THREAD

**Issue by singhPrasan** [airavata-courses/madrinathapa#2]
**Testing on Ubuntu**
I was able to install all dependencies required for the Services to run by modifying the command as : sudo npm install -g seneca --save #1 .

Cannot find module 'seneca' and 'seneca-web' while running commands "node greet-service.js" and "node index.js" inside /hello-world. 
Screenshot attached.

![error](https://user-images.githubusercontent.com/22266716/29851363-b1b828d2-8d01-11e7-9003-fd912af5621a.png)

**Comment by madrinathapa** [comment]
Hi Prasandeep,

I update the readme file yesterday. I am so sorry for the confusion. Could you please uninstall seneca and install it and all the other modules in the order? Doing so might solve the issue. 

Thank you,
Madrina Thapa

**Comment by singhPrasan** [comment]
@madrinathapa Yes, this works fine after reinstalling the dependencies.
