### ISSUE TITLE
404 on localhost:5000 

### ISSUE THREAD

**Issue by singhPrasan** [airavata-courses/madrinathapa#3]
**Microservice 3 - Square(ASP.NET Core)**

i.Navigate to /Assignment1/Services/Square
  Execute: dotnet restore---------------------------------------**Works**
ii.Navigate to /Assignment1/Services/Square
  Execute: dotnet build------------------------------------------**Works**
iii.Navigate to /Assignment1/Services/Square/Square
  Execute: dotnet run------------------------------------------**Server starts but gives 404 on localhost:5000**

![serverrunning](https://user-images.githubusercontent.com/22266716/29852044-c5f40948-8d05-11e7-90f7-e0ccea069299.png)
![404](https://user-images.githubusercontent.com/22266716/29852043-c5ecb03a-8d05-11e7-9102-3436e568d622.png)

**Comment by madrinathapa** [comment]
The link to the service is:
http://localhost:5000/api/square/4

Here square is the name of the controller and 4 is the parameter

**Comment by singhPrasan** [comment]
Thanks for the link. It works!
