### ISSUE TITLE
request for some additinal steps for installing ASP.NET Core 1.1

### ISSUE THREAD

**Issue by satyamsah** [airavata-courses/madrinathapa#6]
Hi Madrina, 

I saw lot of boilerplate steps for installing ASP.NET Core 1.1 in ubuntu. Could you please refine the steps.

Also, I installed ASP.NET Core 1.1 using : "https://go.microsoft.com/fwlink/?LinkID=835009" and tried to execute your steps in Windows System.

I got the following error:

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet restore

    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Could you please highlight the specific steps for this installation

**Comment by satyamsah** [comment]
Kindly could you please add proper steps for install the asp .net for linux based servers in your readme:

https://www.microsoft.com/net/core#linuxubuntu

**Comment by satyamsah** [comment]
You can  highlight steps to install .net sdk for other OSs in installing ASP.NET Core 1.1.

https://www.microsoft.com/net/core

**Comment by satyamsah** [comment]
Hi Madrina,
Any of  the dotnet command not working inspite of installing all the dependency from 

https://www.microsoft.com/net/core#linuxubuntu :

(myenv) ubuntu524@ubuntu524-VirtualBox:~/madrinathapa/Assignment1/Services/Square$ dotnet restore
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
(myenv) ubuntu524@ubuntu524-VirtualBox:~/madrinathapa/Assignment1/Services/Square$ dotnet build
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
(myenv) ubuntu524@ubuntu524-VirtualBox:~/madrinathapa/Assignment1/Services/Square$  dotnet run
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409


Kindly check and let me know. If you want screen share of my machine, we can do it online

**Comment by madrinathapa** [comment]
Hi Satyam,

I have updated the README with installation details. Please before installing make sure that you have removed all the previous versions of .NET Core.

Thank you,
Madrina Thapa

**Comment by satyamsah** [comment]
Ok thanks. I would do the same and let you know

**Comment by satyamsah** [comment]
You application is not working because storage issue as it is error of in `dotnet restore` command. This command is also consuming resource of approx .1 GB while running. 


If you want I can do screen share,so that can debug.

**Comment by madrinathapa** [comment]
Hello Satyam,

Yes, we can do a screen share and debug. 

Thank you,
Madrina Thapa
