### ISSUE TITLE
Java server auto closing

### ISSUE THREAD

**Issue by singhPrasan** [airavata-courses/madrinathapa#7]
After running the command <./mvnw spring-boot:run>, the server starts but gets auto closed. Screenshot of  error log attached.

![java-server-error](https://user-images.githubusercontent.com/22266716/29984755-ba3ac56c-8f29-11e7-8311-0f0f2d62b1cc.png)

**Comment by madrinathapa** [comment]
Hello Prasandeep,

I have created a new branch and updated the code. Here's the link to it - https://github.com/airavata-courses/madrinathapa/tree/Assignment1_NewDevelop 

Please check it out and let me know. 

Thank you,
Madrina Thapa

**Comment by singhPrasan** [comment]
@madrinathapa checked the given branch. It's working and I am able to get output for all the three microservices
