### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/madrinathapa#8]
<img width="909" alt="screen shot 2017-09-07 at 4 17 19 pm" src="https://user-images.githubusercontent.com/13809837/30189337-0e8f9648-93e8-11e7-888c-7b61ad21a108.png">

Why do you have steps 1 and 3? Aren't they both to run the Circle service?

**Comment by madrinathapa** [comment]
Hi Sneha,  

Yes, you are right. I put it by mistake and I am not using that service anymore. So, you don't have to run that service. I will update the readme now. 

Thank you,
Madrina Thapa
